<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ITW.Domain\ITW.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Infrastructure\" />
		<Folder Include="Integration\" />
		<Folder Include="Shared\" />
	</ItemGroup>

</Project>
