// <auto-generated />
using System;
using ITW.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITW.Infrastructure.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260507101035_AddLagermanagement")]
    partial class AddLagermanagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITW.Application.Aktivitaet.AktivitaetsEintrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Bereich")
                        .HasColumnType("int");

                    b.Property<string>("IconCssClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Kategorie")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("Zeitpunkt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Bereich", "Zeitpunkt")
                        .HasDatabaseName("IX_AktivitaetsLog_Bereich_Zeitpunkt");

                    b.ToTable("AktivitaetsLog", (string)null);
                });

            modelBuilder.Entity("ITW.Application.Aufgaben.Aufgabe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Bereich")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ErledigtAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("Faelligkeitsdatum")
                        .HasColumnType("date");

                    b.Property<int>("Prioritaet")
                        .HasColumnType("int");

                    b.Property<int>("Quelle")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SystemSchluessel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("SystemSchluessel")
                        .HasDatabaseName("IX_Aufgaben_SystemSchluessel");

                    b.HasIndex("Bereich", "Status")
                        .HasDatabaseName("IX_Aufgaben_Bereich_Status");

                    b.ToTable("Aufgaben", (string)null);
                });

            modelBuilder.Entity("ITW.Dienstplan.Domain.Entities.AutoplanLernereignis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AusfallGrundCode")
                        .HasColumnType("int");

                    b.Property<string>("BearbeitetVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BesetzungsSlotCode")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DienstDatum")
                        .HasColumnType("date");

                    b.Property<Guid>("DienstplanPeriodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EreignisTypCode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ErfasstAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("KontextArztUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KontextNotfallsanitaeter1UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KontextNotfallsanitaeter2UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NeueUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UrspruenglichGeplanterUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VorherigeUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ErfasstAm")
                        .HasDatabaseName("IX_AutoplanLernereignisse_ErfasstAm");

                    b.HasIndex("DienstplanPeriodeId", "DienstDatum")
                        .HasDatabaseName("IX_AutoplanLernereignisse_Periode_Datum");

                    b.ToTable("AutoplanLernereignisse", (string)null);
                });

            modelBuilder.Entity("ITW.Dienstplan.Domain.Entities.DienstplanPeriode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Jahr")
                        .HasColumnType("int");

                    b.Property<int>("Monat")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PlanFreigegebenAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlanFreigegebenVonUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PlanIstFreigegeben")
                        .HasColumnType("bit");

                    b.Property<bool>("WunschphaseIstOffen")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PlanIstFreigegeben")
                        .HasDatabaseName("IX_DienstplanPerioden_PlanIstFreigegeben");

                    b.HasIndex("WunschphaseIstOffen")
                        .HasDatabaseName("IX_DienstplanPerioden_WunschphaseIstOffen");

                    b.HasIndex("Jahr", "Monat")
                        .IsUnique()
                        .HasDatabaseName("IX_DienstplanPerioden_Jahr_Monat");

                    b.ToTable("DienstplanPerioden", (string)null);
                });

            modelBuilder.Entity("ITW.Dienstplan.Domain.Entities.Dienstwunsch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DienstplanPeriodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("WunschDatum")
                        .HasColumnType("date");

                    b.Property<int>("WunschTyp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DienstplanPeriodeId", "UserId", "WunschDatum")
                        .IsUnique()
                        .HasDatabaseName("IX_DienstplanWuensche_Periode_User_Datum");

                    b.ToTable("DienstplanWuensche", (string)null);
                });

            modelBuilder.Entity("ITW.Dienstplan.Domain.Entities.FreelancerMonatswunsch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AktualisiertAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DienstplanPeriodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GewuenschteDienste")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DienstplanPeriodeId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_FreelancerMonatswuensche_Periode_User");

                    b.ToTable("FreelancerMonatswuensche", (string)null);
                });

            modelBuilder.Entity("ITW.Dienstplan.Domain.Entities.GeplanterDienstTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AktualisiertAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AktualisiertVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArztUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DienstDatum")
                        .HasColumnType("date");

                    b.Property<Guid>("DienstplanPeriodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notfallsanitaeter1UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notfallsanitaeter2UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DienstplanPeriodeId", "DienstDatum")
                        .IsUnique()
                        .HasDatabaseName("IX_GeplanteDiensttage_Periode_Datum");

                    b.ToTable("GeplanteDiensttage", (string)null);
                });

            modelBuilder.Entity("ITW.Dienstplan.Domain.Entities.GeplanterDienstTagAusfall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AusfallGrundCode")
                        .HasColumnType("int");

                    b.Property<int>("BesetzungsSlotCode")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DienstDatum")
                        .HasColumnType("date");

                    b.Property<Guid>("DienstplanPeriodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ErfasstAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErfasstVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UrspruenglichGeplanterUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VertretungsUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DienstplanPeriodeId", "DienstDatum", "BesetzungsSlotCode")
                        .IsUnique()
                        .HasDatabaseName("IX_GeplanteDiensttagAusfaelle_Periode_Datum_Slot");

                    b.ToTable("GeplanteDiensttagAusfaelle", (string)null);
                });

            modelBuilder.Entity("ITW.Domain.Organisation.Entities.BenutzerBereichszuordnung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Bereich")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeaktiviertAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Fuehrungsverantwortung")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("Rolle")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ZugewiesenAm")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Bereich", "IsActive", "IsPrimary")
                        .HasDatabaseName("IX_BenutzerBereichszuordnungen_Bereich_Aktiv_Primaer");

                    b.HasIndex("UserId", "IsActive", "IsPrimary")
                        .HasDatabaseName("IX_BenutzerBereichszuordnungen_User_Aktiv_Primaer");

                    b.ToTable("BenutzerBereichszuordnungen", (string)null);
                });

            modelBuilder.Entity("ITW.Domain.Organisation.Entities.ModulZuweisung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Bereich")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeaktiviertAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeaktiviertVonUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("bit");

                    b.Property<int>("Modul")
                        .HasColumnType("int");

                    b.Property<int>("Rolle")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ZugewiesenAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZugewiesenVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Bereich", "Rolle", "IstAktiv")
                        .HasDatabaseName("IX_ModulZuweisungen_Bereich_Rolle_Aktiv");

                    b.HasIndex("Modul", "Bereich", "Rolle")
                        .IsUnique()
                        .HasDatabaseName("IX_ModulZuweisungen_Modul_Bereich_Rolle");

                    b.ToTable("ModulZuweisungen", (string)null);
                });

            modelBuilder.Entity("ITW.Domain.Personnel.Entities.AllgemeinesMitarbeiterprofil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AktualisiertAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Beschaeftigungsart")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Hausnummer")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ort")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Postleitzahl")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Strasse")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefonnummer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_AllgemeineMitarbeiterprofile_UserId");

                    b.ToTable("AllgemeineMitarbeiterprofile", (string)null);
                });

            modelBuilder.Entity("ITW.Domain.Personnel.Entities.ItwMitarbeiterQualifikation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IstHauptqualifikation")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItwMitarbeiterprofilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QualifikationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ZugewiesenAm")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("QualifikationId");

                    b.HasIndex("ItwMitarbeiterprofilId", "QualifikationId")
                        .IsUnique()
                        .HasDatabaseName("IX_ItwMitarbeiterQualifikationen_Profil_Qualifikation");

                    b.ToTable("ItwMitarbeiterQualifikationen", (string)null);
                });

            modelBuilder.Entity("ITW.Domain.Personnel.Entities.ItwMitarbeiterprofil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AktualisiertAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ItwMitarbeiterprofile_UserId");

                    b.ToTable("ItwMitarbeiterprofile", (string)null);
                });

            modelBuilder.Entity("ITW.Domain.Personnel.Entities.MitarbeiterDokument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DateigroesseBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("DateinameOriginal")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTimeOffset>("HochgeladenAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HochgeladenVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Inhaltstyp")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Speicherpfad")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_MitarbeiterDokumente_UserId");

                    b.HasIndex("UserId", "HochgeladenAm")
                        .HasDatabaseName("IX_MitarbeiterDokumente_UserId_HochgeladenAm");

                    b.ToTable("MitarbeiterDokumente", (string)null);
                });

            modelBuilder.Entity("ITW.Domain.Personnel.Qualifications.ItwQualifikation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAktiv")
                        .HasColumnType("bit");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_ItwQualifikationen_Code");

                    b.ToTable("ItwQualifikationen", (string)null);
                });

            modelBuilder.Entity("ITW.Domain.Security.Entities.PasswortResetAnfrage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AngefordertAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("BearbeitetAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("BearbeitetVonUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Bereich")
                        .HasColumnType("int");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Bereich", "Status")
                        .HasDatabaseName("IX_PasswortResetAnfragen_Bereich_Status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_PasswortResetAnfragen_User_Status");

                    b.ToTable("PasswortResetAnfragen", (string)null);
                });

            modelBuilder.Entity("ITW.Fahrzeugmanagement.Domain.Entities.FahrtenbuchEintrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AktualisiertAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AktualisiertVonUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BeifahrerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Bemerkung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("EinsatzId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EndKilometerstand")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndzeitUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FahrerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FahrerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FahrtKategorie")
                        .HasColumnType("int");

                    b.Property<string>("Fahrtzweck")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("FahrzeugId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GefahreneKilometer")
                        .HasColumnType("int");

                    b.Property<bool>("IstAutomatischVorbelegt")
                        .HasColumnType("bit");

                    b.Property<int?>("KilometerstandBeimTanken")
                        .HasColumnType("int");

                    b.Property<Guid?>("RouteSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StartKilometerstand")
                        .HasColumnType("int");

                    b.Property<string>("Startort")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("StartzeitUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TankmengeLiter")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Zielort")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("EinsatzId")
                        .HasDatabaseName("IX_FahrtenbuchEintraege_EinsatzId");

                    b.HasIndex("RouteSessionId")
                        .HasDatabaseName("IX_FahrtenbuchEintraege_RouteSessionId");

                    b.HasIndex("FahrerUserId", "StartzeitUtc")
                        .HasDatabaseName("IX_FahrtenbuchEintraege_Fahrer_StartzeitUtc");

                    b.HasIndex("FahrzeugId", "StartzeitUtc")
                        .HasDatabaseName("IX_FahrtenbuchEintraege_Fahrzeug_StartzeitUtc");

                    b.ToTable("FahrtenbuchEintraege", (string)null);
                });

            modelBuilder.Entity("ITW.Fahrzeugmanagement.Domain.Entities.Fahrzeug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AktualisiertAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AktualisiertVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Baujahr")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("Erstzulassung")
                        .HasColumnType("date");

                    b.Property<string>("Fahrzeugtyp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hersteller")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InterneNummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kennzeichen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KilometerstandAktuell")
                        .HasColumnType("int");

                    b.Property<int>("Kraftstoffart")
                        .HasColumnType("int");

                    b.Property<int?>("LeistungKw")
                        .HasColumnType("int");

                    b.Property<string>("Modell")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StandardStandort")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Kennzeichen")
                        .IsUnique()
                        .HasDatabaseName("UX_Fahrzeuge_Kennzeichen");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Fahrzeuge_Status");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasDatabaseName("UX_Fahrzeuge_Vin");

                    b.ToTable("Fahrzeuge", (string)null);
                });

            modelBuilder.Entity("ITW.Fahrzeugmanagement.Domain.Entities.FahrzeugDokument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FahrzeugId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("GueltigBis")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("HochgeladenAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HochgeladenVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Kategorie")
                        .HasColumnType("int");

                    b.Property<string>("Speicherpfad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FahrzeugId", "Kategorie")
                        .HasDatabaseName("IX_FahrzeugDokumente_Fahrzeug_Kategorie");

                    b.ToTable("FahrzeugDokumente", (string)null);
                });

            modelBuilder.Entity("ITW.Fahrzeugmanagement.Domain.Entities.FahrzeugFahrerzuordnung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bemerkung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("FahrzeugId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("GueltigBis")
                        .HasColumnType("date");

                    b.Property<DateOnly>("GueltigVon")
                        .HasColumnType("date");

                    b.Property<bool>("IstPrimaer")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ZuordnungTyp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FahrzeugId", "UserId", "GueltigVon")
                        .HasDatabaseName("IX_FahrzeugFahrerzuordnungen_Fahrzeug_User_GueltigVon");

                    b.ToTable("FahrzeugFahrerzuordnungen", (string)null);
                });

            modelBuilder.Entity("ITW.Fahrzeugmanagement.Domain.Entities.FahrzeugPruefung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AktualisiertAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AktualisiertVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bemerkung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("FaelligAm")
                        .HasColumnType("date");

                    b.Property<Guid>("FahrzeugId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("LetzteErledigungAm")
                        .HasColumnType("date");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FahrzeugId", "FaelligAm")
                        .HasDatabaseName("IX_FahrzeugPruefungen_Fahrzeug_FaelligAm");

                    b.HasIndex("FahrzeugId", "Typ")
                        .IsUnique()
                        .HasDatabaseName("UX_FahrzeugPruefungen_Fahrzeug_Typ");

                    b.ToTable("FahrzeugPruefungen", (string)null);
                });

            modelBuilder.Entity("ITW.Fahrzeugmanagement.Domain.Entities.FahrzeugTrackingGeraet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LetzterKontaktAm")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique()
                        .HasDatabaseName("UX_FahrzeugTrackingGeraete_DeviceIdentifier");

                    b.ToTable("FahrzeugTrackingGeraete", (string)null);
                });

            modelBuilder.Entity("ITW.Fahrzeugmanagement.Domain.Entities.FahrzeugVertrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anbieter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("BetragProPeriode")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("DokumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("FahrzeugId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("GueltigBis")
                        .HasColumnType("date");

                    b.Property<DateOnly>("GueltigVon")
                        .HasColumnType("date");

                    b.Property<int?>("KuendigungsfristTage")
                        .HasColumnType("int");

                    b.Property<string>("Notiz")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Periodizitaet")
                        .HasColumnType("int");

                    b.Property<int>("VertragTyp")
                        .HasColumnType("int");

                    b.Property<string>("Vertragsnummer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FahrzeugId", "VertragTyp", "GueltigBis")
                        .HasDatabaseName("IX_FahrzeugVertraege_Fahrzeug_VertragTyp_GueltigBis");

                    b.ToTable("FahrzeugVertraege", (string)null);
                });

            modelBuilder.Entity("ITW.Fahrzeugmanagement.Domain.Entities.TrackingGeraetEinrichtungscode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("EingeloestAmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ErstelltAmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVonUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("GueltigBisUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TabletName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .HasDatabaseName("IX_TrackingGeraetEinrichtungscodes_CodeHash");

                    b.HasIndex("EingeloestAmUtc", "GueltigBisUtc")
                        .HasDatabaseName("IX_TrackingGeraetEinrichtungscodes_Status_GueltigBis");

                    b.ToTable("TrackingGeraetEinrichtungscodes", (string)null);
                });

            modelBuilder.Entity("ITW.Fahrzeugmanagement.Domain.Entities.TrackingGeraetStandortAktuell", b =>
                {
                    b.Property<Guid>("TrackingGeraetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AktualisiertAmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("ErfasstAmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("RouteSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SpeedKmh")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("TrackingGeraetId");

                    b.HasIndex("ErfasstAmUtc")
                        .HasDatabaseName("IX_TrackingGeraetStandorteAktuell_ErfasstAmUtc");

                    b.ToTable("TrackingGeraetStandorteAktuell", (string)null);
                });

            modelBuilder.Entity("ITW.Fahrzeugmanagement.Domain.Entities.TrackingGeraetStandortHistorienpunkt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("ErfasstAmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("RouteSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SpeedKmh")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("TrackingGeraetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RouteSessionId", "ErfasstAmUtc")
                        .HasDatabaseName("IX_TrackingGeraetStandortHistorie_RouteSession_ErfasstAmUtc");

                    b.HasIndex("TrackingGeraetId", "ErfasstAmUtc")
                        .HasDatabaseName("IX_TrackingGeraetStandortHistorie_Geraet_ErfasstAmUtc");

                    b.ToTable("TrackingGeraetStandortHistorie", (string)null);
                });

            modelBuilder.Entity("ITW.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ITW.Lagermanagement.Domain.Entities.ArtikelBestand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtikelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Lagerort")
                        .HasColumnType("int");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId", "Lagerort")
                        .IsUnique()
                        .HasDatabaseName("UX_Lager_ArtikelBestand_Artikel_Lagerort");

                    b.ToTable("ArtikelBestand", "Lager");
                });

            modelBuilder.Entity("ITW.Lagermanagement.Domain.Entities.ArtikelCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Ablaufdatum")
                        .HasColumnType("date");

                    b.Property<Guid>("ArtikelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("AusgebuchtAm")
                        .HasColumnType("date");

                    b.Property<string>("AusgebuchtVonUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChargeNummer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<DateOnly>("EingebuchtAm")
                        .HasColumnType("date");

                    b.Property<string>("EingebuchtVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IstAusgebucht")
                        .HasColumnType("bit");

                    b.Property<int>("Lagerort")
                        .HasColumnType("int");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId", "Ablaufdatum")
                        .HasDatabaseName("IX_Lager_ArtikelCharge_Artikel_Ablauf")
                        .HasFilter("[IstAusgebucht] = 0");

                    b.ToTable("ArtikelCharge", "Lager");
                });

            modelBuilder.Entity("ITW.Lagermanagement.Domain.Entities.EinsatzVerbrauch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bemerkung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Fahrzeug")
                        .HasColumnType("int");

                    b.Property<int>("Patienten")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EinsatzVerbrauch", "Lager");
                });

            modelBuilder.Entity("ITW.Lagermanagement.Domain.Entities.EinsatzVerbrauchPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtikelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EinsatzVerbrauchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IstProPatientBerechnet")
                        .HasColumnType("bit");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EinsatzVerbrauchId")
                        .HasDatabaseName("IX_Lager_EinsatzVerbrauchPosition_Verbrauch");

                    b.ToTable("EinsatzVerbrauchPosition", "Lager");
                });

            modelBuilder.Entity("ITW.Lagermanagement.Domain.Entities.LagerArtikel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AktualisiertAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AktualisiertVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BasisEinheit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HatAblaufdatum")
                        .HasColumnType("bit");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("bit");

                    b.Property<int>("Kategorie")
                        .HasColumnType("int");

                    b.Property<int>("Mindestbestand")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PackungsEinheit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PackungsGroesse")
                        .HasColumnType("int");

                    b.Property<decimal?>("VerbrauchProPatient")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Lager_Artikel_Name");

                    b.ToTable("Artikel", "Lager");
                });

            modelBuilder.Entity("ITW.Lagermanagement.Domain.Entities.SauerstoffBewegung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bemerkung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("Datum")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("FlascheId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NachLagerort")
                        .HasColumnType("int");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<int?>("VonLagerort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlascheId", "Datum")
                        .HasDatabaseName("IX_Lager_SauerstoffBewegung_Flasche_Datum");

                    b.ToTable("SauerstoffBewegung", "Lager");
                });

            modelBuilder.Entity("ITW.Lagermanagement.Domain.Entities.SauerstoffFlasche", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVonUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("bit");

                    b.Property<int>("Lagerort")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("VollEingebuchtAmDepot")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Lagerort")
                        .HasDatabaseName("IX_Lager_SauerstoffFlasche_Status_Lagerort")
                        .HasFilter("[IstAktiv] = 1");

                    b.ToTable("SauerstoffFlasche", "Lager");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ITW.Domain.Personnel.Entities.ItwMitarbeiterQualifikation", b =>
                {
                    b.HasOne("ITW.Domain.Personnel.Entities.ItwMitarbeiterprofil", null)
                        .WithMany("Qualifikationen")
                        .HasForeignKey("ItwMitarbeiterprofilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITW.Domain.Personnel.Qualifications.ItwQualifikation", null)
                        .WithMany()
                        .HasForeignKey("QualifikationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ITW.Lagermanagement.Domain.Entities.EinsatzVerbrauchPosition", b =>
                {
                    b.HasOne("ITW.Lagermanagement.Domain.Entities.EinsatzVerbrauch", null)
                        .WithMany("Positionen")
                        .HasForeignKey("EinsatzVerbrauchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ITW.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ITW.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITW.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ITW.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ITW.Domain.Personnel.Entities.ItwMitarbeiterprofil", b =>
                {
                    b.Navigation("Qualifikationen");
                });

            modelBuilder.Entity("ITW.Lagermanagement.Domain.Entities.EinsatzVerbrauch", b =>
                {
                    b.Navigation("Positionen");
                });
#pragma warning restore 612, 618
        }
    }
}
